const mongoose = require('mongoose');
const Product = require('./models/Product');
const User = require('./models/User');
require('dotenv').config();

const products = [
  // Electronics (10 products)
  {
    name: 'iPhone 15 Pro',
    price: 999.99,
    description: 'Latest iPhone with A17 Pro chip, titanium design, and advanced camera system',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300',
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    stock: 50,
    sku: 'IP15PRO-001',
    weight: 0.2,
    tags: ['premium', 'smartphone', '5G'],
    features: ['A17 Pro chip', '48MP camera', 'Titanium build'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Samsung Galaxy S24',
    price: 899.99,
    description: 'Flagship Android phone with stunning display and powerful performance',
    image: 'https://images.unsplash.com/photo-1580910059747-186904ea8eb9?w=300',
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Samsung',
    stock: 45,
    sku: 'SGS24-002',
    weight: 0.21,
    tags: ['android', 'flagship', '5G'],
    features: ['6.8" AMOLED', '5000mAh battery', '50MP zoom'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'MacBook Pro M3',
    price: 2499.99,
    description: 'Professional laptop with M3 chip, perfect for creative work',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    stock: 30,
    sku: 'MBP-M3-003',
    weight: 1.4,
    tags: ['laptop', 'professional', 'apple'],
    features: ['14" Liquid Retina', '18GB RAM', '1TB SSD'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Dell XPS 15',
    price: 1799.99,
    description: 'High-performance Windows laptop with stunning 4K display',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300',
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Dell',
    stock: 25,
    sku: 'XPS15-004',
    weight: 2.1,
    tags: ['laptop', 'windows', '4K'],
    features: ['15.6" 4K OLED', 'Intel i7', '32GB RAM'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Sony WH-1000XM5',
    price: 399.99,
    description: 'Industry leading noise cancelling headphones with exceptional sound',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300',
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'Sony',
    stock: 60,
    sku: 'WH1000XM5-005',
    weight: 0.25,
    tags: ['headphones', 'noise-cancelling', 'premium'],
    features: ['30hr battery', 'Hi-Res Audio', 'Multi-point'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'iPad Air 5',
    price: 599.99,
    description: 'Versatile tablet with M1 chip for work and play',
    image: 'https://images.unsplash.com/photo-1544244015-0e4363665ab0?w=300',
    category: 'Electronics',
    subcategory: 'Tablets',
    brand: 'Apple',
    stock: 40,
    sku: 'IPAD-AIR-006',
    weight: 0.46,
    tags: ['tablet', 'apple', 'm1'],
    features: ['10.9" display', '64GB', 'Touch ID'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Samsung 65" QLED TV',
    price: 1299.99,
    description: 'Stunning 4K QLED TV with smart features',
    image: 'https://images.unsplash.com/photo-1598424154987-054bb309d65f?w=300',
    category: 'Electronics',
    subcategory: 'TVs',
    brand: 'Samsung',
    stock: 15,
    sku: 'QLED65-007',
    weight: 25.5,
    tags: ['tv', '4k', 'smart'],
    features: ['4K QLED', 'Smart TV', 'HDR10+'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Canon EOS R6',
    price: 2499.99,
    description: 'Full-frame mirrorless camera with advanced autofocus',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1c24e49c3?w=300',
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'Canon',
    stock: 12,
    sku: 'EOSR6-008',
    weight: 0.68,
    tags: ['camera', 'mirrorless', 'professional'],
    features: ['20MP full-frame', '4K video', 'Dual AF'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Nintendo Switch',
    price: 299.99,
    description: 'Hybrid gaming console for home and portable play',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99e926?w=300',
    category: 'Electronics',
    subcategory: 'Gaming',
    brand: 'Nintendo',
    stock: 35,
    sku: 'SWITCH-009',
    weight: 0.4,
    tags: ['gaming', 'portable', 'console'],
    features: ['Hybrid console', 'Joy-Con controllers', '32GB storage'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Apple Watch Series 9',
    price: 399.99,
    description: 'Advanced smartwatch with health and fitness tracking',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300',
    category: 'Electronics',
    subcategory: 'Wearables',
    brand: 'Apple',
    stock: 55,
    sku: 'AW9-010',
    weight: 0.12,
    tags: ['smartwatch', 'fitness', 'apple'],
    features: ['Always-On display', 'Blood oxygen sensor', 'Water resistant'],
    isActive: true,
    isFeatured: false
  },

  // Clothing (10 products)
  {
    name: 'Nike Air Max 90',
    price: 129.99,
    description: 'Classic sneakers with iconic design and superior comfort',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300',
    category: 'Clothing',
    subcategory: 'Footwear',
    brand: 'Nike',
    stock: 80,
    sku: 'AIRMAX90-007',
    weight: 0.32,
    tags: ['shoes', 'sneakers', 'classic'],
    features: ['Air Max cushioning', 'Leather upper', 'Rubber outsole'],
    isActive: true,
    isFeatured: true
  },
  {
    name: "Levi's 501 Jeans",
    price: 79.99,
    description: 'Original straight fit jeans, timeless American style',
    image: 'https://images.unsplash.com/photo-1542272606-13e7c2c2d6f1?w=300',
    category: 'Clothing',
    subcategory: 'Jeans',
    brand: 'Levi\'s',
    stock: 120,
    sku: '501-008',
    weight: 0.5,
    tags: ['jeans', 'casual', 'classic'],
    features: ['100% cotton', 'Straight fit', 'Button fly'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Adidas Ultraboost 22',
    price: 189.99,
    description: 'Premium running shoes with responsive cushioning',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300',
    category: 'Clothing',
    subcategory: 'Footwear',
    brand: 'Adidas',
    stock: 65,
    sku: 'ULTRA22-009',
    weight: 0.31,
    tags: ['running', 'shoes', 'performance'],
    features: ['Boost midsole', 'Primeknit upper', 'Continental rubber'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'H&M Cotton T-Shirt',
    price: 19.99,
    description: 'Essential crew neck t-shirt in various colors',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300',
    category: 'Clothing',
    subcategory: 'Tops',
    brand: 'H&M',
    stock: 200,
    sku: 'TSHIRT-010',
    weight: 0.15,
    tags: ['t-shirt', 'casual', 'basic'],
    features: ['100% cotton', 'Regular fit', 'Crew neck'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Zara Blazer',
    price: 89.99,
    description: 'Elegant blazer perfect for business and casual occasions',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=300',
    category: 'Clothing',
    subcategory: 'Jackets',
    brand: 'Zara',
    stock: 45,
    sku: 'BLAZER-011',
    weight: 0.4,
    tags: ['blazer', 'formal', 'versatile'],
    features: ['Polyester blend', 'Notch lapel', 'Two pockets'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'North Face Jacket',
    price: 249.99,
    description: 'Waterproof jacket for outdoor adventures',
    image: 'https://images.unsplash.com/photo-1549637628-4659e5c57a7a?w=300',
    category: 'Clothing',
    subcategory: 'Jackets',
    brand: 'North Face',
    stock: 35,
    sku: 'NFJ-012',
    weight: 0.68,
    tags: ['jacket', 'outdoor', 'waterproof'],
    features: ['Gore-Tex fabric', 'Hood included', 'Adjustable cuffs'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Puma Sweatpants',
    price: 49.99,
    description: 'Comfortable fleece sweatpants for lounging',
    image: 'https://images.unsplash.com/photo-1594634313229-300962c7d161?w=300',
    category: 'Clothing',
    subcategory: 'Bottoms',
    brand: 'Puma',
    stock: 90,
    sku: 'SWEAT-013',
    weight: 0.35,
    tags: ['pants', 'comfortable', 'casual'],
    features: ['Fleece lining', 'Elastic waistband', 'Side pockets'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Under Armour Sports Bra',
    price: 39.99,
    description: 'High-support sports bra for intense workouts',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300',
    category: 'Clothing',
    subcategory: 'Activewear',
    brand: 'Under Armour',
    stock: 75,
    sku: 'BRA-014',
    weight: 0.12,
    tags: ['sports', 'activewear', 'support'],
    features: ['Moisture-wicking', 'High support', 'Breathable mesh'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Gap Hoodie',
    price: 59.99,
    description: 'Classic pullover hoodie with kangaroo pocket',
    image: 'https://images.unsplash.com/photo-1556826794234-5c940fbdde6e?w=300',
    category: 'Clothing',
    subcategory: 'Tops',
    brand: 'Gap',
    stock: 110,
    sku: 'HOODIE-015',
    weight: 0.45,
    tags: ['hoodie', 'casual', 'comfortable'],
    features: ['Cotton blend', 'Kangaroo pocket', 'Ribbed cuffs'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Converse Chuck Taylor',
    price: 59.99,
    description: 'Iconic canvas sneakers with timeless style',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300',
    category: 'Clothing',
    subcategory: 'Footwear',
    brand: 'Converse',
    stock: 95,
    sku: 'CHUCK-016',
    weight: 0.28,
    tags: ['shoes', 'canvas', 'classic'],
    features: ['Canvas upper', 'Rubber sole', 'High-top design'],
    isActive: true,
    isFeatured: false
  },

  // Grocery (10 products)
  {
    name: 'Fresh Organic Apples',
    price: 4.99,
    description: 'Crisp and sweet organic apples, perfect for snacking',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300',
    category: 'Grocery',
    subcategory: 'Fruits',
    brand: 'Local Farm',
    stock: 100,
    sku: 'APPLES-017',
    weight: 0.2,
    tags: ['fruit', 'organic', 'fresh'],
    features: ['Hand-picked', 'No pesticides', 'Locally grown'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Whole Milk',
    price: 3.99,
    description: 'Farm-fresh whole milk from grass-fed cows',
    image: 'https://images.unsplash.com/photo-1550583728-b13199b31e5e?w=300',
    category: 'Grocery',
    subcategory: 'Dairy',
    brand: 'Local Farm',
    stock: 150,
    sku: 'MILK-018',
    weight: 1.0,
    tags: ['dairy', 'fresh', 'natural'],
    features: ['Pasteurized', '3.25% fat', 'Vitamin D'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Organic Eggs',
    price: 5.99,
    description: 'Free-range organic eggs from happy chickens',
    image: 'https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?w=300',
    category: 'Grocery',
    subcategory: 'Dairy',
    brand: 'Happy Chickens',
    stock: 80,
    sku: 'EGGS-019',
    weight: 0.6,
    tags: ['eggs', 'organic', 'protein'],
    features: ['12 eggs per carton', 'Free-range', 'No hormones'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Whole Wheat Bread',
    price: 3.49,
    description: 'Nutritious whole wheat bread for healthy meals',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300',
    category: 'Grocery',
    subcategory: 'Bakery',
    brand: 'Local Bakery',
    stock: 90,
    sku: 'BREAD-024',
    weight: 0.5,
    tags: ['bread', 'healthy', 'whole-grain'],
    features: ['100% whole wheat', 'No preservatives', 'Fresh daily'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Bananas',
    price: 149,
    description: 'Sweet and creamy bananas, rich in potassium',
    image: 'https://picsum.photos/seed/bananas/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Fruits',
    brand: 'Tropical Imports',
    stock: 120,
    sku: 'BANANAS-025',
    weight: 0.25,
    tags: ['fruit', 'tropical', 'healthy'],
    features: ['Fair trade', 'Ripe and ready', 'High in potassium'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Organic Tomatoes',
    price: 399,
    description: 'Vine-ripened organic tomatoes, perfect for salads',
    image: 'https://picsum.photos/seed/organictomatoes/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Vegetables',
    brand: 'Green Valley',
    stock: 70,
    sku: 'TOMATOES-026',
    weight: 0.15,
    tags: ['vegetables', 'organic', 'fresh'],
    features: ['Pesticide-free', 'Vine-ripened', 'Local farm'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Chicken Breast',
    price: 699,
    description: 'Premium boneless chicken breast, high in protein',
    image: 'https://picsum.photos/seed/chickenbreast/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Meat',
    brand: 'Local Butcher',
    stock: 60,
    sku: 'CHICKEN-027',
    weight: 0.5,
    tags: ['meat', 'protein', 'fresh'],
    features: ['Hormone-free', 'Boneless', 'Lean cuts'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Greek Yogurt',
    price: 349,
    description: 'Creamy Greek yogurt, high in protein',
    image: 'https://picsum.photos/seed/greekyogurt/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Dairy',
    brand: 'Dairy Fresh',
    stock: 85,
    sku: 'YOGURT-028',
    weight: 0.32,
    tags: ['dairy', 'protein', 'healthy'],
    features: ['10% fat', 'Live cultures', 'No artificial flavors'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Avocados',
    price: 699,
    description: 'Ripe avocados perfect for toast and salads',
    image: 'https://picsum.photos/seed/avocados/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Fruits',
    brand: 'Tropical Imports',
    stock: 65,
    sku: 'AVO-029',
    weight: 0.18,
    tags: ['fruit', 'healthy', 'avocado'],
    features: ['Ripe when delivered', 'Rich in healthy fats', 'Perfect ripeness'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Orange Juice',
    price: 349,
    description: 'Fresh squeezed orange juice, not from concentrate',
    image: 'https://picsum.photos/seed/orangejuice/300/300.jpg',
    category: 'Grocery',
    subcategory: 'Beverages',
    brand: 'Citrus Grove',
    stock: 95,
    sku: 'OJ-030',
    weight: 1.0,
    tags: ['juice', 'fresh', 'vitamin'],
    features: ['100% orange juice', 'No added sugar', 'Vitamin C rich'],
    isActive: true,
    isFeatured: false
  },

  // Books (10 products)
  {
    name: 'The Great Gatsby',
    price: 999,
    description: 'Classic American novel about the Jazz Age',
    image: 'https://picsum.photos/seed/greatgatsby/300/300.jpg',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'F. Scott Fitzgerald',
    stock: 85,
    sku: 'GATSBY-031',
    weight: 0.3,
    tags: ['classic', 'literature', 'american'],
    features: ['Hardcover', '208 pages', 'Penguin Classics'],
    isActive: true,
    isFeatured: true
  },
  {
    name: '1984',
    price: 1099,
    description: 'Dystopian masterpiece about totalitarian surveillance',
    image: 'https://picsum.photos/seed/1984book/300/300.jpg',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'George Orwell',
    stock: 95,
    sku: 'NINETEEN84-032',
    weight: 0.35,
    tags: ['classic', 'dystopian', 'literature'],
    features: ['Paperback', '328 pages', 'Signet Classics'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Atomic Habits',
    price: 1299,
    description: 'Guide to building good habits and breaking bad ones',
    image: 'https://picsum.photos/seed/atomichabits/300/300.jpg',
    category: 'Books',
    subcategory: 'Self-Help',
    brand: 'James Clear',
    stock: 120,
    sku: 'ATOMIC-033',
    weight: 0.4,
    tags: ['self-help', 'productivity', 'habits'],
    features: ['Hardcover', '320 pages', 'New York Times Bestseller'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'The Lean Startup',
    price: 1499,
    description: 'Essential guide for entrepreneurs and startups',
    image: 'https://picsum.photos/seed/leanstartup/300/300.jpg',
    category: 'Books',
    subcategory: 'Business',
    brand: 'Eric Ries',
    stock: 75,
    sku: 'LEAN-034',
    weight: 0.45,
    tags: ['business', 'startup', 'entrepreneur'],
    features: ['Paperback', '336 pages', 'Entrepreneur\'s must-read'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'JavaScript Guide',
    price: 2499,
    description: 'Comprehensive guide to modern JavaScript development',
    image: 'https://picsum.photos/seed/javascriptguide/300/300.jpg',
    category: 'Books',
    subcategory: 'Programming',
    brand: 'Various Authors',
    stock: 50,
    sku: 'JS-GUIDE-035',
    weight: 0.6,
    tags: ['programming', 'javascript', 'technical'],
    features: ['Paperback', '512 pages', 'Code examples included'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'To Kill a Mockingbird',
    price: 1199,
    description: 'Powerful story about racial injustice in the American South',
    image: 'https://picsum.photos/seed/tokillamockingbird/300/300.jpg',
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Harper Lee',
    stock: 88,
    sku: 'MOCKINGBIRD-036',
    weight: 0.32,
    tags: ['classic', 'fiction', 'american'],
    features: ['Paperback', '376 pages', 'Penguin Classics'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Rich Dad Poor Dad',
    price: 1399,
    description: 'Financial education book about wealth building',
    image: 'https://picsum.photos/seed/richdaddoordad/300/300.jpg',
    category: 'Books',
    subcategory: 'Finance',
    brand: 'Robert Kiyosaki',
    stock: 92,
    sku: 'RICHDAD-037',
    weight: 0.38,
    tags: ['finance', 'wealth', 'education'],
    features: ['Paperback', '266 pages', 'International bestseller'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'The Psychology of Money',
    price: 1599,
    description: 'Understanding the relationship between psychology and wealth',
    image: 'https://picsum.photos/seed/psychologyofmoney/300/300.jpg',
    category: 'Books',
    subcategory: 'Finance',
    brand: 'Morgan Housel',
    stock: 78,
    sku: 'PSYCHMONEY-038',
    weight: 0.42,
    tags: ['finance', 'psychology', 'money'],
    features: ['Hardcover', '256 pages', 'Wall Street Journal Bestseller'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Clean Code',
    price: 2799,
    description: 'Handbook of agile software craftsmanship',
    image: 'https://picsum.photos/seed/cleancode/300/300.jpg',
    category: 'Books',
    subcategory: 'Programming',
    brand: 'Robert C. Martin',
    stock: 45,
    sku: 'CLEANCODE-039',
    weight: 0.55,
    tags: ['programming', 'software', 'development'],
    features: ['Paperback', '464 pages', 'Developer essential'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Sapiens',
    price: 1599,
    description: 'Brief history of humankind from Stone Age to modern times',
    image: 'https://picsum.photos/seed/sapiens/300/300.jpg',
    category: 'Books',
    subcategory: 'History',
    brand: 'Yuval Noah Harari',
    stock: 105,
    sku: 'SAPIENS-040',
    weight: 0.48,
    tags: ['history', 'humanity', 'non-fiction'],
    features: ['Paperback', '443 pages', 'Global bestseller'],
    isActive: true,
    isFeatured: false
  },

  // Sports (10 products)
  {
    name: 'Yoga Mat',
    price: 2499,
    description: 'Non-slip exercise mat for yoga and fitness',
    image: 'https://picsum.photos/seed/yogamat/300/300.jpg',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'YogaPro',
    stock: 100,
    sku: 'YOGA-MAT-041',
    weight: 1.2,
    tags: ['yoga', 'fitness', 'exercise'],
    features: ['Non-slip surface', '6mm thick', 'Eco-friendly material'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Dumbbells Set',
    price: 7499,
    description: 'Adjustable dumbbell set for home workouts',
    image: 'https://picsum.photos/seed/dumbbells/300/300.jpg',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'FitGear',
    stock: 40,
    sku: 'DUMBBELL-042',
    weight: 8.5,
    tags: ['fitness', 'weights', 'exercise'],
    features: ['Adjustable 5-50lbs', 'Rubber coating', 'Compact storage'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Running Shoes',
    price: 6999,
    description: 'Lightweight running shoes with responsive cushioning',
    image: 'https://picsum.photos/seed/runningshoes/300/300.jpg',
    category: 'Sports',
    subcategory: 'Running',
    brand: 'Nike',
    stock: 55,
    sku: 'RUN-SHOES-043',
    weight: 0.28,
    tags: ['running', 'shoes', 'athletic'],
    features: ['Breathable mesh', 'Responsive foam', 'Durable outsole'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Tennis Racket',
    price: 12499,
    description: 'Professional grade tennis racket for competitive play',
    image: 'https://picsum.photos/seed/tennisracket/300/300.jpg',
    category: 'Sports',
    subcategory: 'Tennis',
    brand: 'Wilson',
    stock: 30,
    sku: 'TENNIS-044',
    weight: 0.32,
    tags: ['tennis', 'racket', 'sports'],
    features: ['Graphite frame', '16x19 string pattern', '4 1/2 grip size'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Basketball',
    price: 2499,
    description: 'Official size basketball for indoor and outdoor play',
    image: 'https://picsum.photos/seed/basketball/300/300.jpg',
    category: 'Sports',
    subcategory: 'Basketball',
    brand: 'Spalding',
    stock: 80,
    sku: 'BASKETBALL-045',
    weight: 0.62,
    tags: ['basketball', 'sports', 'indoor'],
    features: ['Official NBA size', 'Rubber cover', 'Indoor/outdoor use'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Soccer Ball',
    price: 2099,
    description: 'Professional match soccer ball with excellent grip',
    image: 'https://picsum.photos/seed/soccerball/300/300.jpg',
    category: 'Sports',
    subcategory: 'Soccer',
    brand: 'Adidas',
    stock: 65,
    sku: 'SOCCER-046',
    weight: 0.45,
    tags: ['soccer', 'ball', 'sports'],
    features: ['Size 5', 'Thermally bonded', 'Water-resistant'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Resistance Bands Set',
    price: 1699,
    description: '5-level resistance bands for full body workouts',
    image: 'https://picsum.photos/seed/resistancebands/300/300.jpg',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'FitLife',
    stock: 120,
    sku: 'BANDS-047',
    weight: 0.15,
    tags: ['fitness', 'resistance', 'exercise'],
    features: ['5 resistance levels', 'Portable', 'Door anchor included'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Golf Clubs Set',
    price: 49999,
    description: 'Complete set of golf clubs for all skill levels',
    image: 'https://picsum.photos/seed/golfclubs/300/300.jpg',
    category: 'Sports',
    subcategory: 'Golf',
    brand: 'Callaway',
    stock: 15,
    sku: 'GOLF-048',
    weight: 8.2,
    tags: ['golf', 'clubs', 'sports'],
    features: ['12 clubs', 'Graphite shafts', 'Stand bag included'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Swimming Goggles',
    price: 1399,
    description: 'Anti-fog swimming goggles with UV protection',
    image: 'https://picsum.photos/seed/swimminggoggles/300/300.jpg',
    category: 'Sports',
    subcategory: 'Swimming',
    brand: 'Speedo',
    stock: 90,
    sku: 'GOGGLES-049',
    weight: 0.08,
    tags: ['swimming', 'goggles', 'water'],
    features: ['Anti-fog coating', 'UV protection', 'Silicone strap'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Jump Rope',
    price: 1099,
    description: 'Speed jump rope for cardio workouts',
    image: 'https://picsum.photos/seed/jumprope/300/300.jpg',
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'FitGear',
    stock: 140,
    sku: 'JUMPROPE-050',
    weight: 0.25,
    tags: ['fitness', 'cardio', 'exercise'],
    features: ['Adjustable length', 'Ball bearing handles', 'Non-slip grip'],
    isActive: true,
    isFeatured: false
  },

  // Home (10 products)
  {
    name: 'Coffee Maker',
    price: 7499,
    description: 'Programmable coffee maker with thermal carafe',
    image: 'https://picsum.photos/seed/coffeemaker/300/300.jpg',
    category: 'Home',
    subcategory: 'Kitchen',
    brand: 'Black+Decker',
    stock: 60,
    sku: 'COFFEE-051',
    weight: 2.1,
    tags: ['kitchen', 'appliance', 'coffee'],
    features: ['12-cup capacity', 'Programmable', 'Thermal carafe'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Blender',
    price: 4199,
    description: 'High-speed blender for smoothies and food prep',
    image: 'https://picsum.photos/seed/blender/300/300.jpg',
    category: 'Home',
    subcategory: 'Kitchen',
    brand: 'Ninja',
    stock: 70,
    sku: 'BLENDER-052',
    weight: 1.8,
    tags: ['kitchen', 'appliance', 'blender'],
    features: ['1000W motor', '72oz pitcher', 'Dishwasher safe'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Vacuum Cleaner',
    price: 16999,
    description: 'Powerful cordless vacuum with HEPA filtration',
    image: 'https://picsum.photos/seed/vacuumcleaner/300/300.jpg',
    category: 'Home',
    subcategory: 'Cleaning',
    brand: 'Dyson',
    stock: 45,
    sku: 'VACUUM-053',
    weight: 3.2,
    tags: ['cleaning', 'home', 'appliance'],
    features: ['Cordless', '60min battery', 'HEPA filter'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Desk Lamp',
    price: 2999,
    description: 'Modern LED desk lamp with adjustable brightness',
    image: 'https://picsum.photos/seed/desklamp/300/300.jpg',
    category: 'Home',
    subcategory: 'Furniture',
    brand: 'Simple Designs',
    stock: 85,
    sku: 'DESK-LAMP-054',
    weight: 0.8,
    tags: ['lighting', 'home', 'office'],
    features: ['LED technology', 'Adjustable arm', 'Touch control'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Throw Pillows Set',
    price: 3499,
    description: 'Set of 2 decorative throw pillows for couch',
    image: 'https://picsum.photos/seed/throwpillows/300/300.jpg',
    category: 'Home',
    subcategory: 'Decor',
    brand: 'Home Essentials',
    stock: 90,
    sku: 'PILLOWS-055',
    weight: 0.6,
    tags: ['decor', 'home', 'cushions'],
    features: ['Machine washable', 'Hidden zipper', 'Soft fill'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Wall Clock',
    price: 2099,
    description: 'Silent wall clock with modern minimalist design',
    image: 'https://picsum.photos/seed/wallclock/300/300.jpg',
    category: 'Home',
    subcategory: 'Decor',
    brand: 'TimeKeeper',
    stock: 110,
    sku: 'CLOCK-056',
    weight: 0.45,
    tags: ['decor', 'home', 'timekeeping'],
    features: ['Silent movement', '12" diameter', 'Battery operated'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Kitchen Knife Set',
    price: 6999,
    description: 'Professional 6-piece stainless steel knife set',
    image: 'https://picsum.photos/seed/kitchenknives/300/300.jpg',
    category: 'Home',
    subcategory: 'Kitchen',
    brand: 'Chef\'s Choice',
    stock: 55,
    sku: 'KNIVES-057',
    weight: 1.5,
    tags: ['kitchen', 'cooking', 'tools'],
    features: ['High-carbon steel', 'Ergonomic handles', 'Wood block'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Air Purifier',
    price: 12999,
    description: 'HEPA air purifier for clean indoor air',
    image: 'https://picsum.photos/seed/airpurifier/300/300.jpg',
    category: 'Home',
    subcategory: 'Appliances',
    brand: 'PureAir',
    stock: 35,
    sku: 'PURIFIER-058',
    weight: 2.8,
    tags: ['air', 'purifier', 'health'],
    features: ['HEPA filter', '350 sq ft coverage', 'Quiet operation'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Bed Sheets Set',
    price: 5299,
    description: 'Luxury cotton bed sheets, queen size',
    image: 'https://picsum.photos/seed/bedsheets/300/300.jpg',
    category: 'Home',
    subcategory: 'Bedding',
    brand: 'Comfort Living',
    stock: 75,
    sku: 'SHEETS-059',
    weight: 1.2,
    tags: ['bedding', 'cotton', 'comfort'],
    features: ['100% Egyptian cotton', '400 thread count', 'Deep pockets'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Storage Ottoman',
    price: 7999,
    description: 'Versatile storage ottoman with hidden compartment',
    image: 'https://picsum.photos/seed/storageottoman/300/300.jpg',
    category: 'Home',
    subcategory: 'Furniture',
    brand: 'Storage Solutions',
    stock: 40,
    sku: 'OTTOMAN-060',
    weight: 4.5,
    tags: ['furniture', 'storage', 'versatile'],
    features: ['Hidden storage', 'Upholstered top', 'Sturdy construction'],
    isActive: true,
    isFeatured: true
  },

  // Other (10 products)
  {
    name: 'Wireless Mouse',
    price: 2499,
    description: 'Ergonomic wireless mouse with precision tracking',
    image: 'https://picsum.photos/seed/wirelessmouse/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Logitech',
    stock: 150,
    sku: 'MOUSE-061',
    weight: 0.15,
    tags: ['computer', 'accessories', 'wireless'],
    features: ['2.4GHz connection', 'AA batteries', '6-month battery'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'USB-C Hub',
    price: 3499,
    description: '7-in-1 USB-C hub with multiple connectivity options',
    image: 'https://picsum.photos/seed/usbchub/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Anker',
    stock: 120,
    sku: 'HUB-062',
    weight: 0.08,
    tags: ['computer', 'accessories', 'connectivity'],
    features: ['4K HDMI', 'SD card reader', '100W power delivery'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Power Bank',
    price: 4199,
    description: '20000mAh portable charger with fast charging',
    image: 'https://picsum.photos/seed/powerbank/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Xiaomi',
    stock: 95,
    sku: 'BANK-063',
    weight: 0.43,
    tags: ['mobile', 'accessories', 'power'],
    features: ['20000mAh capacity', 'USB-C output', 'LED indicator'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Bluetooth Speaker',
    price: 6999,
    description: 'Portable waterproof speaker with 360° sound',
    image: 'https://picsum.photos/seed/bluetoothspeaker/300/300.jpg',
    category: 'Other',
    subcategory: 'Audio',
    brand: 'JBL',
    stock: 110,
    sku: 'SPEAKER-064',
    weight: 0.65,
    tags: ['audio', 'portable', 'bluetooth'],
    features: ['IPX7 waterproof', '12hr battery', 'Party mode'],
    isActive: true,
    isFeatured: true
  },
  {
    name: 'Laptop Stand',
    price: 2999,
    description: 'Adjustable aluminum laptop stand for better ergonomics',
    image: 'https://picsum.photos/seed/laptopstand/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Rainbow Design',
    stock: 80,
    sku: 'STAND-065',
    weight: 0.85,
    tags: ['computer', 'accessories', 'ergonomic'],
    features: ['Aluminum build', 'Adjustable height', 'Heat dissipation'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Smart Watch',
    price: 16999,
    description: 'Fitness tracker with heart rate monitor and GPS',
    image: 'https://picsum.photos/seed/smartwatch/300/300.jpg',
    category: 'Other',
    subcategory: 'Wearables',
    brand: 'Fitbit',
    stock: 70,
    sku: 'WATCH-066',
    weight: 0.12,
    tags: ['fitness', 'wearables', 'smart'],
    features: ['Heart rate monitor', 'GPS tracking', '7-day battery'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Desk Organizer',
    price: 2099,
    description: 'Bamboo desk organizer for better workspace management',
    image: 'https://picsum.photos/seed/deskorganizer/300/300.jpg',
    category: 'Other',
    subcategory: 'Office',
    brand: 'EcoDesk',
    stock: 130,
    sku: 'ORGANIZER-067',
    weight: 0.95,
    tags: ['office', 'organization', 'desk'],
    features: ['Bamboo material', '5 compartments', 'Phone holder'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Phone Case',
    price: 1699,
    description: 'Protective clear case with shock absorption',
    image: 'https://picsum.photos/seed/phonecase/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Spigen',
    stock: 200,
    sku: 'CASE-068',
    weight: 0.05,
    tags: ['mobile', 'protection', 'accessories'],
    features: ['Clear design', 'Shock proof', 'Wireless charging compatible'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'HDMI Cable',
    price: 1299,
    description: 'High-speed 4K HDMI cable 6 feet long',
    image: 'https://picsum.photos/seed/hdmicable/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'AmazonBasics',
    stock: 250,
    sku: 'HDMI-069',
    weight: 0.12,
    tags: ['cables', 'connectivity', 'video'],
    features: ['4K@60Hz support', 'Gold-plated connectors', '6ft length'],
    isActive: true,
    isFeatured: false
  },
  {
    name: 'Webcam HD',
    price: 5999,
    description: '1080p HD webcam with auto-focus and noise reduction',
    image: 'https://picsum.photos/seed/webcam/300/300.jpg',
    category: 'Other',
    subcategory: 'Accessories',
    brand: 'Logitech',
    stock: 85,
    sku: 'WEBCAM-066',
    weight: 0.18,
    tags: ['camera', 'webcam', 'video'],
    features: ['1080p resolution', 'Auto-focus', 'Noise-cancelling mic'],
    isActive: true,
    isFeatured: true
  }
];

const seedProducts = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGO_URI);
    console.log('🔄 Connected to MongoDB');

    // Get or create a default user for product ownership
    let defaultUser = await User.findOne({ email: 'admin@ecommerce.com' });
    if (!defaultUser) {
      const bcrypt = require('bcryptjs');
      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash('admin123', salt);
      
      defaultUser = new User({
        name: 'Admin User',
        email: 'admin@ecommerce.com',
        password: hashedPassword,
        role: 'admin'
      });
      await defaultUser.save();
      console.log('✅ Created default admin user');
    }

    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️ Cleared existing products');

    // Add products with user reference
    const productsWithUser = products.map(product => ({
      ...product,
      createdBy: defaultUser._id
    }));

    await Product.insertMany(productsWithUser);
    console.log(`✅ Added ${products.length} products to database`);

    // Count products by category
    const categoryCounts = await Product.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);
    
    console.log('📊 Products by category:');
    categoryCounts.forEach(cat => {
      console.log(`   ${cat._id}: ${cat.count} products`);
    });

    console.log('🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedProducts();
